### ISSUE TITLE
createconfig with relative path creates broken config.yaml

### ISSUE THREAD

**Issue by manuelpolzhofer** [centrifuge/go-centrifuge#1203]
I used the latest centrifuge binary in a subfolder.

## Reproduce

Create Config Command
```bash
 ./myfolder/centrifuge createconfig -z "ABSOLUTE KEYSTORE PATH" -e "MY INFURA LINK"-n russianhill -t myfolder/ -a 8082 -p 38204
```

## Broken yaml
```yaml
accounts:
  keystore: myfolder//accounts
anchoring:
  precommit: false
centrifugenetwork: russianhill
configstorage:
  path: myfolder//db/centrifuge_config_data.leveldb
ethereum:
  accounts:
    main:
      key: ""
      password: ""
  nodeurl: https://rinkeby.infura.io/v3/f73aca49ee194ac988b31c64c80c6cff
  txpoolaccessenabled: true
identityid: 0x9E1e039D7453B9303B697a3c0d3c8931Ec59879B
keys:
  p2p:
    privatekey: myfolder//p2p.key.pem
    publickey: myfolder//p2p.pub.pem
  signing:
    privatekey: myfolder//signing.key.pem
    publickey: myfolder//signing.pub.pem
nodehostname: 127.0.0.1
nodeport: 8082
notifications:
  endpoint: ""
p2p:
  port: 38204
storage:
  path: myfolder//db/centrifuge_data.leveldb
```

## Problems

- two `//` instead of one `/` for the relative path
- empty key and password
```accounts:
    main:
      key: ""
      password: ""
