### ISSUE TITLE
Improve travis performance 

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#1209]
- cache nixos dependencies
- skip before_install and install in build_artifacts stage

In addition, to have a more deterministic codecov push, let's only push after all tests stages have successfully passed by adding an extra stage that consumes and pushes the individual coverage reports:
```
- stage: "Tests"
      name: "Unit and CMD tests"
      script:
        - ./build/scripts/test_wrapper.sh unit cmd
      after_success:
        - mv coverage.txt unit.cov
...
- stage: "Upload Code Coverage"
      name: "Upload Code Coverage"
      script:
        - bash <(curl -s https://codecov.io/bash) -f "$TRAVIS_BUILD_NUMBER/*.cov"
```
If above doesnt work, push each individual artifact to GCP and pull it from upload coverage stage.
