### ISSUE TITLE
Simplify config.yaml

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#1212]
I would like to take out all account information from the config file, and simplify it with the minimum data needed for the node to start up.

Sample:
```
accounts:
  keystore: hostconfigs/local/Alice/accounts
centrifugenetwork: russianhill
configstorage:
  path: hostconfigs/local/Alice/db/centrifuge_config_data.leveldb
ethereum:
  nodeurl: http://127.0.0.1:9545
p2p_keys:
  privatekey: hostconfigs/local/Alice/p2p.key.pem
  publickey: hostconfigs/local/Alice/p2p.pub.pem
storage:
  path: hostconfigs/local/Alice/db/centrifuge_data.leveldb
# default value for new accounts generated by API
notifications:
  endpoint: http://localhost:8083/webhook
```
