### ISSUE TITLE
Create Node Config

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#481]
Create Node Configuration file with only enough information so the node can start up.

Fields to maintain:
```
storage:
  path: /tmp/centrifuge_data.leveldb // config storage
nodeHostname: 0.0.0.0
nodePort: 8082
p2p:
  externalIP: w.x.y.z
  port: 38202
ethereum:
  nodeURL: http://w.x.y.z:8546
```
