### ISSUE TITLE
createconfig: missing p2p keys usage and creation

### ISSUE THREAD

**Issue by vedhavyas** [centrifuge/go-centrifuge#625]
Created config:

```
...
keys:
  ethauth:
    privatekey: /Users/vedhavyas/datadir/test/ethauth.key.pem
    publickey: /Users/vedhavyas/datadir/test/ethauth.pub.pem
  p2p:
    privatekey: /Users/vedhavyas/datadir/test/p2p.key.pem
    publickey: /Users/vedhavyas/datadir/test/p2p.pub.pem
  signing:
    privatekey: /Users/vedhavyas/datadir/test/signing.key.pem
    publickey: /Users/vedhavyas/datadir/test/signing.pub.pem
...
```

but the p2p.*.pem keys are not created.

Solution: 
Seems like we are not using p2p keys anymore but rather using signing keys.  So, we either remove p2p keys from the node and let the libp2p create keys or we create p2p keys during the `createconfig` and use them for basic host.

I'm leaning towards first one
